language: rust
jobs:
  include:
    - stage: test
      os: linux
      before_script:
        - rustup toolchain install stable
        - rustup component add --toolchain stable clippy-preview || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
        - rustup component add rustfmt
      script:
        - cargo build --verbose
        - cargo test --verbose
        - cargo fmt --all -- --check
        - cargo +stable clippy --all-targets --all-features -- -D warnings -A clippy::unreadable_literal -A clippy::needless_range_loop -A clippy::float_cmp -A clippy::comparison-chain -A clippy::needless-doctest-main -A clippy::missing-safety-doc
    - stage: test
      os: osx
      before_script:
        - rustup toolchain install stable
        - rustup component add --toolchain stable clippy-preview || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
        - rustup component add rustfmt
      script:
        - cargo build --verbose
        - cargo test --verbose
        - cargo fmt --all -- --check
        - cargo +stable clippy --all-targets --all-features -- -D warnings -A clippy::unreadable_literal -A clippy::needless_range_loop -A clippy::float_cmp -A clippy::comparison-chain -A clippy::needless-doctest-main -A clippy::missing-safety-doc