[tasks.build]
command = "cargo"
args = ["build"]

[tasks.make-output-dirs]
command = "mkdir"
args = [
    "-p", 
    "./target/debug/plugin.vst3/Contents/Resources", 
    "./target/debug/plugin.vst3/Contents/x86_64-linux"
]

[tasks.copy-lib]
command = "cp"
args = ["./target/debug/libpassthru.so", "./target/debug/plugin.vst3/Contents/x86_64-linux/plugin.so"]
dependencies = ["build", "make-output-dirs"]

[tasks.all]
dependencies = [
    "make-output-dirs", 
    "build",
    "test", 
    "copy-lib"
]