on: 
  push: 
    branches: 
      - master 
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    name: formatting and linting
    steps:
      - name: checkout  
        uses: actions/checkout@v2
      - name: provision 
        uses: actions-rs/toolchain@v1 
        with: 
          toolchain: stable 
          profile: minimal
          components: rustfmt, clippy 
      - name: cargo fmt 
        uses: actions-rs/cargo@v1 
        with: 
          command: fmt 
          args: --all -- --check
      - name: cargo clippy  
        uses: actions-rs/cargo@v1 
        with: 
          command: clippy 
          args: --all-targets --all-features -- -D warnings

  validate:
    runs-on: ubuntu-latest
    name: validate-linux
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --package again
      - name: Set up plugin
        run: mkdir -p target/debug/again.vst3/Contents/x86_64-linux &&
          mkdir -p target/debug/again.vst3/Contents/Resources &&
          cp target/debug/libagain.so target/debug/again.vst3/Contents/x86_64-linux/again.so
      - uses: actions/checkout@v2
        with:
          repository: steinbergmedia/vst3sdk
          path: vst3sdk
          submodules: recursive
      - name: Install validator dependencies
        run: sudo apt-get install cmake gcc libstdc++6 libx11-xcb-dev libxcb-util-dev
          libxcb-cursor-dev libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev
          libfontconfig1-dev libcairo2-dev libgtkmm-3.0-dev libsqlite3-dev libxcb-keysyms1-dev
      - name: Compile validator
        run: mkdir build && cd build && cmake ../vst3sdk && cmake --build . --config Debug --target validator
      - name: List files
        run: ls -aux
      - name: Validate plugin
        run: ./build/bin/Debug/validator target/debug/again.vst3

  test: 
    strategy:
      matrix: 
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: test 
    steps:
    - uses: actions/checkout@v2 
    - uses: actions-rs/toolchain@v1
      with: 
        toolchain: stable 
        profile: minimal  
    - uses: actions-rs/cargo@v1 
      with: 
        command: test 
        args: --all 